baseurl:          /mate
repository_url:   https://github.com/r4fx/mate
title:            Mate
current_version:  0.2

source:           ./docs_assets
destination:      ./docs
assets:           /docs_assets

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: /:basename/

nav:
  - title: Index
  - title: Grid
  - title: Typography
  - title: Forms
  - title: Buttons
  - title: Icons
  - title: Tables
  - title: Helpers
  - title: Toolbox

exclude: [js, styles, Gemfile, Gemfile.lock]